Repository decide-europa-postproc/Decide_Europa_Postproc, pull requests merged in 2019-01, with the labels that each got.

#11 Mejora de la gestión de incidencias-código
  doc/Gestión de código.md
  doc/Gestión de incidencias.md
Labels: enhancement

#17 Implementado el método Imperiali
  decide/postproc/tests.py
  decide/postproc/views.py
Labels: Medium, enhancement

#18 Se ha actualizado el diario de equipo para el M4. #8
  doc/diario de equipo.pdf
Labels: High
